const mongoose=require('mongoose')
const userSchema=mongoose.Schema({
    fullName:{
        type:String,
        required:true,
        trim:true
    },
    email:{
        type:String,
        required:true,
        trim:true,
        unique:true,
        lowercase:true
    },
    password:{
        type:String,
        required:true,
        trim:true,
        minlength:8
    },
    imageUrl:{
        type:String,
        default:null
    },
    imageId:{
        type:String,
        default:null
    }
})